// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EHYfhn8tYMB0DeK5AHY0ghwVJO0QrLI',
    appId: '1:718704647326:web:33e0f34ef38222493cef8f',
    messagingSenderId: '718704647326',
    projectId: 'scholar-chat-a9ffb',
    authDomain: 'scholar-chat-a9ffb.firebaseapp.com',
    storageBucket: 'scholar-chat-a9ffb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJtXEiRaF6YIv2wpywgtjNMNfSw4RIOng',
    appId: '1:718704647326:android:0c7cdfb3065faac83cef8f',
    messagingSenderId: '718704647326',
    projectId: 'scholar-chat-a9ffb',
    storageBucket: 'scholar-chat-a9ffb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5XvN4DTARLVz-wIx_pJKoemNf_C62FU',
    appId: '1:718704647326:ios:6ed37e44d86415003cef8f',
    messagingSenderId: '718704647326',
    projectId: 'scholar-chat-a9ffb',
    storageBucket: 'scholar-chat-a9ffb.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5XvN4DTARLVz-wIx_pJKoemNf_C62FU',
    appId: '1:718704647326:ios:6ed37e44d86415003cef8f',
    messagingSenderId: '718704647326',
    projectId: 'scholar-chat-a9ffb',
    storageBucket: 'scholar-chat-a9ffb.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EHYfhn8tYMB0DeK5AHY0ghwVJO0QrLI',
    appId: '1:718704647326:web:b997d953c6455efe3cef8f',
    messagingSenderId: '718704647326',
    projectId: 'scholar-chat-a9ffb',
    authDomain: 'scholar-chat-a9ffb.firebaseapp.com',
    storageBucket: 'scholar-chat-a9ffb.firebasestorage.app',
  );
}
